name: PR workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.GHAP_AWS_REGION }}
          aws-access-key-id: ${{ secrets.GHAP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHAP_AWS_SECRET_ACCESS_KEY }}

      - name: Sync allure-report folder
        run: |
          aws s3 sync ./docs/daily/api/allure-report ${{ secrets.GHAP_S3_BUCKET_URL }}/try/ghap/allure-report --delete
