name: Simple dummy workflow
on: push

jobs:
  dummy_job_1:
    name: Dummy job 1
    runs-on: ubuntu-20.04
    env:
      FLAG: Job 1 flag
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Print location
        run: pwd

      - name: Print contents
        run: ls
