name: Simple dummy workflow
on:
  push:
    branches:
      - "trunk"
  workflow_dispatch:

env:
  E2E_PLAYWRIGHT: false

jobs:
  job_1:
    name: Archive job summary
    runs-on: ubuntu-20.04

    steps:
      - name: Run if E2E_PLAYWRIGHT is true
        if: fromJSON(env.E2E_PLAYWRIGHT)
        run: echo "I ran!"

      - name: Run if E2E_PLAYWRIGHT is false
        if: !fromJSON(env.E2E_PLAYWRIGHT)
        run: echo "I ran!"
