name: Simple dummy workflow
on:
  push:
    branches:
      - "trunk"
  workflow_dispatch:

jobs:
  dummy_job_1:
    name: Archive job summary
    runs-on: ubuntu-20.04
    steps:
      - name: Make dir
        run: mkdir -p output

      - run: |
          echo $GITHUB_STEP_SUMMARY
          echo "hello world" >> $GITHUB_STEP_SUMMARY
          cp $GITHUB_STEP_SUMMARY output

      - run: ls output
