name: Simple dummy workflow
on: workflow_dispatch
inputs:
  flag_value:
    description: Flag value
    required: true
    default: 0

jobs:
  dummy_job:
    name: Dummy job
    runs-on: ubuntu-20.04
    steps:
      - name: Print flag value
        if: Boolean(github.event.inputs.flag_value)
        run: echo $FLAG
