name: Simple dummy workflow
on: push

jobs:
  dummy_job_1:
    name: Dummy job 1
    runs-on: ubuntu-20.04
    env:
      FLAG: Job 1 flag
    steps:
      - name: Print FLAG value
        run: |
          echo "FLAG = $FLAG"

  dummy_job_2:
    name: Dummy job 2
    needs: [dummy_job_1]
    runs-on: ubuntu-20.04
    steps:
      - name: Print FLAG value from job 1
        env:
          FLAG_2: ${{ needs.job_1.env.FLAG }}
        run: |
            echo "FLAG_2 = $FLAG_2"
