name: Simple dummy workflow
on: push

jobs:
  dummy_job:
    name: Dummy job
    runs-on: ubuntu-20.04
    env:
      FLAG: ${{ true }}
    steps:
      - name: Run this step when FLAG is true
        if: env.FLAG
        run: |
          echo "FLAG = true"

      - name: Run this step when FLAG is false
        if: ${{ !env.FLAG }}
        run: |
          echo "FLAG = false"
