name: Simple dummy workflow
on:
  push:
    branches:
      - "trunk"
  workflow_dispatch:

env:
  E2E_PLAYWRIGHT: true

jobs:
  job_1:
    name: Archive job summary
    runs-on: ubuntu-20.04

    steps:
      - name: Is true
        if: fromJSON(env.E2E_PLAYWRIGHT)
        run: echo "If you see this, it means that E2E_PLAYWRIGHT was set to 'true'"
