name: Simple dummy workflow
on: workflow_dispatch

jobs:
  dummy_job:
    name: Dummy job
    runs-on: ubuntu-20.04
    env:
      FLAG: ${{ true }}
    steps:
      - name: Print non-existing env var
        if: env.FLAG
        run: echo $FLAG
