name: Simple dummy workflow
on: push

jobs:
  dummy_job:
    name: Dummy job
    runs-on: ubuntu-20.04
    env:
      FLAG: blah
    steps:
      - name: Run this step when FLAG is true
        if: fromJSON(env.FLAG)
        run: |
          echo "FLAG = $FLAG"

      - name: Run this step when FLAG is false
        if: ${{ !fromJSON(env.FLAG) }}
        run: |
          echo "FLAG = $FLAG"
